export const errors = {
  WRONG_INPUT: 'WRONG_INPUT',
  FILE_DOES_NOT_EXIST: 'FILE_DOES_NOT_EXIST',
  INTERSECTION_FAILED: 'INTERSECTION_FAILED',
  PARSED_INTERSECTION_FAILED: 'PARSED_INTERSECTION_FAILED',
};
