export const errors = {
  NO_THEME: 'NO_THEME',
  NO_THEME_NAME: 'NO_THEME_NAME',
  NO_THEME_VARIABLES: 'NO_THEME_VARIABLES',
  INTERSECTION_FAILED: 'INTERSECTION_FAILED',
  FILE_DOES_NOT_EXIST: 'FILE_DOES_NOT_EXIST',
  EMPTY_THEME_VARIABLE: 'EMPTY_THEME_VARIABLE',
} as const;
